
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_ROOT_DATABASE: restaurant-booking-demo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env.dev
    environment:
      PORT: 4000
      MONGO_URI: mongodb://root:mypassword@mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      args:
        VITE_API_URL: "http://localhost:4000/graphql"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data: