
type Reservation {
  _id: ObjectId!
  confirmationCode: String!
  restaurantId: ObjectId!
  tableId: ObjectId!
  partySize: Int!
  arrival: DateTime!
  firstName: String!
  lastName: String!
  email: String!
  message: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Mutation {
  addReservation(
    firstName: String!,
    lastName: String!,
    email: String!,
    message: String,
    arrival: DateTime!, 
    partySize: Int!,
    tableId: ObjectId!
    ): Reservation! @public
}