
type Mutation {
  addRestaurant(  
    name: String!,
    adress: String!,
    openingDays: [WeekDays!]!,
    openingHours: OpeningHoursInput!,
    sittings: [SittingInput!]!
  ): Restaurant!

  updateRestaurant(
    restaurantId: ObjectId!,
    name: String,
    adress: String,
    openingDays: [WeekDays!],
    openingHours: OpeningHoursInput,
    sittings: [SittingInput!]
  ):Restaurant!

  addMenuItem(
    restaurantId: ObjectId!, 
    categoryName: CategoryName!,
    name: String!,
    description: String,
    price: Float!,
    vegetarian: Boolean!
    ): MenuItem!

  removeMenuItem(
    restaurantId: ObjectId!,
    itemId: ObjectId!
  ): Boolean!

  updateMenuItem(
    restaurantId: ObjectId!,
    itemId: ObjectId!,
    categoryName: CategoryName,
    name: String,
    description: String,
    price: Float,
    vegetarian: Boolean
  ): MenuItem!
}

type Query {
    getMenu(restaurantId: ObjectId!): [MenuCategory!]! @public 
    getAllRestaurants: [RestaurantDto!]! @public
    getAvailableSittings(restaurantId: ObjectId!, partySize: Int!): [DateTime!]! @public
}

input OpeningHoursInput {
  open: String!
  close: String!
}

input SittingInput {
  startTime: String!
  durationMinutes: Int!
}

type RestaurantDto {
  _id: ObjectId!,
  name: String,
  adress: String!
  openingDays: [WeekDays!]!
  openingHours: OpeningHours!
  sittings: [Sitting!]!
}

type OpeningHours {
  open: String!,
  close: String!
}

type Restaurant {
  _id: ObjectId!
  name: String!
  adress: String!
  openingDays: [WeekDays!]!
  openingHours: OpeningHours!
  sittings: [Sitting!]!
  menu: [MenuCategory!]!
}

enum WeekDays {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}

type Sitting {
  startTime: String!
  durationMinutes: Int!
}

type MenuCategory {
  category: String!
  items: [MenuItem!]!
}

type MenuItem {
  _id: ObjectId!
  name: String!
  description: String
  price: Int!
  vegetarian: Boolean!
}

enum CategoryName {
  BREAKFAST
  LUNCH
  DINNER
  APPETIZERS
  DESSERTS
  DRINKS
}