
type Mutation {

  addTable(
    restaurantId: ObjectId!
    name: String!
    seats: Int!
  ): Table!

  updateTable(
    tableId: ObjectId!
    name: String
    seats: Int
    ): Table!

    removeTable(tableId: ObjectId!): Table!

    undoTableRemoval(tableId: ObjectId!): Table!
}

type Query {
  getTables(restaurantId: ObjectId!): [Table!]!
}


type Table {
  _id: ObjectId!
  restaurantId: ObjectId!
  name: String!
  seats: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  removedAt: DateTime
  removed: Boolean
}
