
type Query {
  getTables(restaurantId: ObjectId!): [Table!]!
}


type Table {
  _id: ObjectId!
  restaurantId: ObjectId!
  name: String!
  seats: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type TableDto {
  _id: ObjectId!
  restaurantId: ObjectId!
  availableDates: [DateTime!]!
}
