
enum Role {
  USER
  ADMIN
}

type User {
  _id: ObjectId!
  name: String!
  email: String!
  password: String!
  role: Role!
}

type UserDto {
  _id: ObjectId!
  name: String!
}

type Query {
  me: UserDto!
  users: [User!]!
  userByName(name: String!): User
}

type Mutation {
  addUser(name: String!, email: String!, password: String!): User!
}