
enum Role {
  USER
  ADMIN
}

type User {
  _id: ObjectId!
  name: String!
  email: String!
  password: String! # hashed and private
  role: Role!
}

type Query {
  user(_id: ObjectId!): User
  users: [User!]! @public
  userByName(name: String!): User
}

type Mutation {
  addUser(name: String!, email: String!, password: String!): User!
}